// <auto-generated />
namespace BTL_LTQL_1721050522_Trinh_Thu_Huong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_Table_KHENTHUONGKYLUAT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_Table_KHENTHUONGKYLUAT));
        
        string IMigrationMetadata.Id
        {
            get { return "202103031814138_Create_Table_KHENTHUONGKYLUAT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
